// dashboard/src/plugins/nut/install.vue
<script setup lang="ts">
import { reactive } from "vue";

import SharedLinks from "./users/SharedLinks.vue";
import { EMAIL_VALIDATOR } from "../../components/form";

interface FormState {
  email: string;
  realName: string;
  nickName: string;
  password: string;
  passwordConfirmation: string;
  remember: boolean;
  captcha: string;
}
const formState = reactive<FormState>({
  email: "",
  realName: "",
  nickName: "",
  password: "",
  passwordConfirmation: "",
  captcha: "",
  remember: true,
});
const onFinish = (values: any) => {
  console.log("Success:", values);
};
</script>

<template>
  <SharedLinks :title="$t('pages.install.title')">
    <a-form
      :model="formState"
      name="basic"
      :label-col="{ span: 8 }"
      autocomplete="off"
      @finish="onFinish"
    >
      <a-form-item
        :label="$t('fields.email')"
        name="email"
        :rules="EMAIL_VALIDATOR"
      >
        <a-input v-model:value="formState.email" />
      </a-form-item>
      <a-form-item
        :label="$t('fields.real-name')"
        name="realName"
        :rules="[{ required: true }]"
      >
        <a-input v-model:value="formState.realName" />
      </a-form-item>
      <a-form-item
        :label="$t('fields.nick-name')"
        name="nickName"
        :rules="[{ required: true }]"
      >
        <a-input v-model:value="formState.nickName" />
      </a-form-item>
      <a-form-item
        :label="$t('fields.password')"
        name="password"
        :rules="[{ required: true }]"
      >
        <a-input-password v-model:value="formState.password" />
      </a-form-item>

      <a-form-item
        :label="$t('fields.password-confirmation')"
        name="passwordConfirmation"
        :rules="[{ required: true }]"
      >
        <a-input-password v-model:value="formState.passwordConfirmation" />
      </a-form-item>
      <a-form-item
        :label="$t('fields.captcha')"
        name="captcha"
        :rules="[{ required: true }]"
        :wrapperCol="{ span: 4 }"
      >
        <a-input v-model:value="formState.captcha" />
      </a-form-item>

      <a-form-item name="remember" :wrapper-col="{ offset: 6, span: 22 }">
        <a-checkbox v-model:checked="formState.remember">{{
          $t("fields.remember-me")
        }}</a-checkbox>
      </a-form-item>

      <a-form-item :wrapper-col="{ offset: 6, span: 22 }">
        <a-button type="primary" html-type="submit">{{
          $t("buttons.submit")
        }}</a-button>
      </a-form-item>
    </a-form>
  </SharedLinks>
</template>

<style scoped></style>

// dashboard/src/pages/install.tsx
import { useState, useEffect } from 'react';
import { useIntl, getLocale } from 'umi';
import { Form, Input, message, Button } from 'antd';
import moment from 'moment-timezone';

import NonSignInForm from '@/components/NonSignInForm';
import {
  CODE_VALIDATOR,
  EMAIL_VALIDATOR,
  NAME_VALIDATOR,
  PASSWORD_VALIDATOR,
} from '@/components/form';
import { graphql } from '@/global';

export default () => {
  const intl = useIntl();

  const onFinish = (values: any) => {
    console.log('Success:', values);
    graphql(
      `
        mutation Install($user: UserSignUpRequest!) {
          install(form: $user) {
            createdAt
          }
        }
      `,
      {
        user: {
          nickName: values.nickName,
          realName: values.realName,
          email: values.email,
          password: values.password,
          lang: getLocale(),
          timeZone: moment.tz.guess(),
          home: document.location.origin,
        },
      },
      (res: any) => {
        message.success(intl.formatMessage({ id: 'flashes.successed' }));
      },
    );
  };

  return (
    <NonSignInForm title={intl.formatMessage({ id: 'install.title' })}>
      <Form name="install" layout="vertical" onFinish={onFinish}>
        <Form.Item
          label={intl.formatMessage({ id: 'attributes.nick-name' })}
          name="nickName"
          rules={[CODE_VALIDATOR]}
        >
          <Input />
        </Form.Item>
        <Form.Item
          label={intl.formatMessage({ id: 'attributes.email' })}
          name="email"
          rules={[EMAIL_VALIDATOR]}
        >
          <Input />
        </Form.Item>
        <Form.Item
          label={intl.formatMessage({ id: 'attributes.real-name' })}
          name="realName"
          rules={[NAME_VALIDATOR]}
        >
          <Input />
        </Form.Item>
        <Form.Item
          label={intl.formatMessage({ id: 'attributes.password' })}
          name="password"
          rules={[PASSWORD_VALIDATOR]}
        >
          <Input.Password type="password" />
        </Form.Item>
        <Form.Item
          label={intl.formatMessage({ id: 'attributes.password-confirmation' })}
          name="passwordConfirmation"
          rules={[
            { required: true },
            ({ getFieldValue }) => ({
              validator(_, value) {
                if (!value || getFieldValue('password') === value) {
                  return Promise.resolve();
                }
                return Promise.reject(
                  new Error(
                    intl.formatMessage({
                      id: 'helpers.password-onfirmation',
                    }),
                  ),
                );
              },
            }),
          ]}
        >
          <Input.Password type="password" />
        </Form.Item>

        <Form.Item
          wrapperCol={{
            sm: { offset: 2, span: 20 },
            md: { offset: 4, span: 16 },
          }}
        >
          <Button type="primary" htmlType="submit">
            {intl.formatMessage({
              id: 'buttons.submit',
            })}
          </Button>
        </Form.Item>
      </Form>
    </NonSignInForm>
  );
};
